module.exports = [
////HP
	{	item: 6552,
		name: "高级HP恢复药水",
		cd: 10,
		hp: true,
		use_at: 50,
		inCd: false, id: 0, invQtd: 0 },
	{	item: 114,
		name: "联盟补给品 : 急速恢复药水",
		cd: 30,
		hp: true,
		use_at: 35,
		inCd: false, id: 0, invQtd: 0 },
	{	item: 111,
		name: "持续性恢复药水",
		cd: 30,
		hp: true,
		use_at: 15,
		inCd: false, id: 0, invQtd: 0 },
	{	item: 149644,
		name: "联盟补给品 : 持续性恢复药水",
		cd: 30,
		hp: true,
		use_at: 15,
		inCd: false, id: 0, invQtd: 0 },
	{	item: 221225,
		name: "凯亚的号角喇叭",
		cd: 30,
		hp: true,
		use_at: 8,
		inCd: false, id: 0, invQtd: 0 },
////MP
	{	item: 6560,
		name: "低级MP恢复药水",
		cd: 10,
		hp: false,
		use_at: 20,
		inCd: false, id: 0, invQtd: 0 },
	{	item: 6561,
		name: "中级MP恢复药水",
		cd: 10,
		hp: false,
		use_at: 30,
		inCd: false, id: 0, invQtd: 0 },
	{	item: 6562,
		name: "高级MP恢复药水",
		cd: 10,
		hp: false,
		use_at: 40,
		inCd: false, id: 0, invQtd: 0 }
]
